name: build and push docker image, deploy to heroku

on:
  push:
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Login to DockerHub
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
      uses: docker/login-action@v1 
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and push
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: xelladze22/algo-aio:latest

    - name: Deploy to heroku
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
      id: heroku
      uses: jctaveras/heroku-deploy@v3.1.0 
      with:
        email: ${{ secrets.HEROKU_EMAIL }} 
        api_key: ${{ secrets.HEROKU_API_KEY }} 
        app_name: 'algo-aio' 
        dockerfile_path: '.'
        process_type: 'web' 
